# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Master Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4


### Setup .NET ###    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  

        
### Build and Publish ###
    - name: Build and Publish
      run: |
           dotnet restore  
           dotnet build --output build_output
           dotnet publish --output publish_output


### Test the build ###
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

### List publish directory ###  
    - name: List publish directory
      run: Get-ChildItem -Path publish_output
      shell: pwsh


### Compress To Zip ###
    - name: Compress To Zip
      run: |
           cd publish_output
           Compress-Archive -Path . -DestinationPath ../output.zip
      shell: pwsh

           
### Upload ZIP ###
    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with: 
         name: test
         path: output.zip


### Copy files to Restore ###
    - name: Copy files to Restore
      run: |
           $sitePath = "C:\inetpub\wwwroot\BO-Stage\Site"
           $restorePath = "C:\inetpub\wwwroot\BO-Stage\Restore"
           
           # Check permissions
           try {
               $testFile = Join-Path -Path $sitePath -ChildPath "testqwerty.txt"
               New-Item -Path $testFile -ItemType File -Force
               Write-Output "Permissions check successful."
           } catch {
               Write-Error "Failed to check permissions: $_"
               exit 1
           }

           # Create Restore directory if it doesn't exist
           if (-Not (Test-Path -Path $restorePath)) {
               try {
                   New-Item -ItemType Directory -Path $restorePath -ErrorAction Stop
                   Write-Output "Created Restore directory."
               } catch {
                   Write-Error "Failed to create Restore directory: $_"
                   exit 1
               }
           }

           # Copy files from Site to Restore
           if (Test-Path -Path $sitePath) {
               try {
                   Copy-Item -Path $sitePath\* -Destination $restorePath -Recurse -Force -ErrorAction Stop
                   Write-Output "Files copied successfully."
               } catch {
                   Write-Error "Failed to copy files: $_"
                   exit 1
               }
           } else {
               Write-Host "Site directory not found. Skipping copy operation."
           }
      shell: pwsh
