# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Master Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  
    - name: Build and Publish
      run: |
           dotnet restore  
           dotnet build --output build_output
           dotnet publish --output publish_output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: List publish directory
      run: ls -la publish_output
    - name: CompressToZip
      run: |
           cd publish_output           
           zip -r ../output.zip .
    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with: 
         name: test
         path: output.zip
         
    - name: Copy files to restore
      run: |
           if (-Not (Test-Path -Path "C:\inetpub\wwwroot\BO-Stage\Restore")) {
             New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\BO-Stage\Restore"
           }
           Copy-Item -Path "C:\inetpub\wwwroot\BO-Stage\Site\*" -Destination "C:\inetpub\wwwroot\BO-Stage\Restore" -Recurse -Force
      shell: pwsh
