# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Master Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4


### Setup .NET ###    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  

        
### Build and Publish ###
    - name: Build and Publish
      run: |
           dotnet restore  
           dotnet build --output build_output
           dotnet publish --output publish_output


### Test the build ###
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

### List publish directory ###  
    - name: List publish directory
      run: Get-ChildItem -Path publish_output
      shell: pwsh


### Compress To Zip ###
    - name: Compress To Zip
      run: |
           cd publish_output
           Compress-Archive -Path . -DestinationPath ../output.zip
      shell: pwsh

           
### Upload ZIP ###
    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with: 
         name: test
         path: output.zip


### Copy files to Restore ###
    - name: Copy files to Restore
      run: |
           $sitePath = "C:\inetpub\wwwroot\BO-Stage\Site"
           $restorePath = "C:\inetpub\wwwroot\BO-Stage\Restore"
           
           if (-Not (Test-Path -Path $restorePath)) {
             New-Item -ItemType Directory -Path $restorePath
           }

           if (Test-Path -Path $sitePath) {
             Copy-Item -Path $sitePath\* -Destination $restorePath -Recurse -Force
           } else {
             Write-Host "Site directory not found. Skipping copy operation."
           }
      shell: pwsh
