# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  
    - name: Build and Publish
      run: |
           dotnet restore  
           dotnet build
           dotnet publish -o publish 
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: CompressToZip
      run: |
           cd publish           
           zip -r ../output.
    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with: 
         name: test
         path: ./publish
